name: "CI: Action"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  exemple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a lista files
        run: ls -la
